export default [
  // ── PROTEIN ─────────────────────────────────
  {
    name: 'Chicken Breast',
    category: 'Protein',
    unit: 'g',
    gramsPerUnit: 1,
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
  },
  {
    name: 'Chicken Curry',
    category: 'Protein',
    unit: 'g',
    gramsPerUnit: 1,
    calories: 150,
    protein: 12,
    carbs: 5,
    fat: 8,
  },
  {
    name: 'Whole Egg',
    category: 'Protein',
    unit: 'piece',
    gramsPerUnit: 50,
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
  },
  {
    name: 'Egg White',
    category: 'Protein',
    unit: 'piece',
    gramsPerUnit: 33,
    calories: 52,
    protein: 11,
    carbs: 0.7,
    fat: 0.2,
  },
  {
    name: 'Whey Protein',
    category: 'Protein',
    unit: 'scoop',
    gramsPerUnit: 30,
    calories: 120,
    protein: 24,
    carbs: 3,
    fat: 1.5,
  },
  {
    name: 'Protein Bar',
    category: 'Protein',
    unit: 'piece',
    gramsPerUnit: 60,
    calories: 200,
    protein: 20,
    carbs: 22,
    fat: 6,
  },
  {
    name: 'Tuna (canned)',
    category: 'Protein',
    unit: 'g',
    gramsPerUnit: 1,
    calories: 116,
    protein: 26,
    carbs: 0,
    fat: 1,
  },
 
  // ── DAIRY ────────────────────────────────────
  {
    name: 'Paneer',
    category: 'Dairy',
    unit: 'g',
    gramsPerUnit: 1,
    calories: 265,
    protein: 18,
    carbs: 1.2,
    fat: 20,
  },
  {
    name: 'Curd (Dahi)',
    category: 'Dairy',
    unit: 'g',
    gramsPerUnit: 1,
    calories: 98,
    protein: 3.5,
    carbs: 3.4,
    fat: 4.3,
  },
  {
    name: 'Greek Yogurt',
    category: 'Dairy',
    unit: 'g',
    gramsPerUnit: 1,
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
  },
  {
    name: 'Milk (Full Fat)',
    category: 'Dairy',
    unit: 'ml',
    gramsPerUnit: 1,
    calories: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
  },
  {
    name: 'Milk (Toned)',
    category: 'Dairy',
    unit: 'ml',
    gramsPerUnit: 1,
    calories: 44,
    protein: 3.5,
    carbs: 4.5,
    fat: 1.5,
  },
 
  // ── CARBS ────────────────────────────────────
  {
    name: 'White Rice (cooked)',
    category: 'Carbs',
    unit: 'g',
    gramsPerUnit: 1,
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
  },
  {
    name: 'Brown Rice (cooked)',
    category: 'Carbs',
    unit: 'g',
    gramsPerUnit: 1,
    calories: 122,
    protein: 2.6,
    carbs: 26,
    fat: 1,
  },
  {
    name: 'Roti (Wheat)',
    category: 'Carbs',
    unit: 'piece',
    gramsPerUnit: 40,
    calories: 104,
    protein: 3.1,
    carbs: 18,
    fat: 2.7,
  },
  {
    name: 'Oats',
    category: 'Carbs',
    unit: 'g',
    gramsPerUnit: 1,
    calories: 389,
    protein: 17,
    carbs: 66,
    fat: 7,
  },
  {
    name: 'Bread (White)',
    category: 'Carbs',
    unit: 'piece',
    gramsPerUnit: 30,
    calories: 265,
    protein: 9,
    carbs: 49,
    fat: 3.2,
  },
  {
    name: 'Bread (Brown)',
    category: 'Carbs',
    unit: 'piece',
    gramsPerUnit: 30,
    calories: 247,
    protein: 13,
    carbs: 41,
    fat: 4.2,
  },
  {
    name: 'Sweet Potato',
    category: 'Carbs',
    unit: 'g',
    gramsPerUnit: 1,
    calories: 86,
    protein: 1.6,
    carbs: 20,
    fat: 0.1,
  },
  {
    name: 'Maggi (1 packet)',
    category: 'Carbs',
    unit: 'piece',
    gramsPerUnit: 70,
    calories: 340,
    protein: 7,
    carbs: 47,
    fat: 14,
  },
  {
    name: 'Banana',
    category: 'Fruit',
    unit: 'piece',
    gramsPerUnit: 120,
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
  },
 
  // ── FAT ──────────────────────────────────────
  {
    name: 'Peanut Butter',
    category: 'Fat',
    unit: 'tbsp',
    gramsPerUnit: 16,
    calories: 588,
    protein: 25,
    carbs: 20,
    fat: 50,
  },
  {
    name: 'Almonds',
    category: 'Fat',
    unit: 'g',
    gramsPerUnit: 1,
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 50,
  },
  {
    name: 'Cashews',
    category: 'Fat',
    unit: 'g',
    gramsPerUnit: 1,
    calories: 553,
    protein: 18,
    carbs: 30,
    fat: 44,
  },
  {
    name: 'Ghee',
    category: 'Fat',
    unit: 'tbsp',
    gramsPerUnit: 13,
    calories: 900,
    protein: 0,
    carbs: 0,
    fat: 100,
  },
 
  // ── VEGETABLES ───────────────────────────────
  {
    name: 'Dal (Cooked)',
    category: 'Vegetable',
    unit: 'g',
    gramsPerUnit: 1,
    calories: 116,
    protein: 9,
    carbs: 20,
    fat: 0.4,
  },
  {
    name: 'Rajma (Cooked)',
    category: 'Vegetable',
    unit: 'g',
    gramsPerUnit: 1,
    calories: 127,
    protein: 8.7,
    carbs: 22,
    fat: 0.5,
  },
  {
    name: 'Chickpeas (Cooked)',
    category: 'Vegetable',
    unit: 'g',
    gramsPerUnit: 1,
    calories: 164,
    protein: 8.9,
    carbs: 27,
    fat: 2.6,
  },
  {
    name: 'Spinach',
    category: 'Vegetable',
    unit: 'g',
    gramsPerUnit: 1,
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
  },
  {
    name: 'Broccoli',
    category: 'Vegetable',
    unit: 'g',
    gramsPerUnit: 1,
    calories: 34,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
  },
 
  // ── FRUIT ────────────────────────────────────
  {
    name: 'Apple',
    category: 'Fruit',
    unit: 'piece',
    gramsPerUnit: 150,
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
  },
 
  // ── BEVERAGE ─────────────────────────────────
  {
    name: 'Black Coffee',
    category: 'Beverage',
    unit: 'ml',
    gramsPerUnit: 1,
    calories: 2,
    protein: 0.3,
    carbs: 0,
    fat: 0,
  },
  {
    name: 'Green Tea',
    category: 'Beverage',
    unit: 'ml',
    gramsPerUnit: 1,
    calories: 1,
    protein: 0,
    carbs: 0.2,
    fat: 0,
  },
]